kind: Deployment
apiVersion: apps/v1
metadata:
  name: webhook-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-store
  template:
    metadata:
      labels:
        app: webhook-store
    spec:
      containers:
        - name: webhook-store
          image: webhook-store:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: webhook-store
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: webhook-store